Global:
  image_dir: assets/samples/tiny_cls/images
  kie_model_dir: assets/samples/models/kie_tiny.modelstub
  ser_model_dir: assets/samples/models/kie_ser_tiny.modelstub
  re_model_dir: assets/samples/models/kie_re_tiny.modelstub
  det_model_dir: assets/samples/models/det_tiny.modelstub
  rec_model_dir: assets/samples/models/rec_tiny.modelstub
  rec_char_dict_path: assets/samples/tiny_rec/dict.txt

Architecture:
  model_type: kie
