Global:
  device: cuda
  use_amp: true
  epoch_num: 10
  save_model_dir: ./output/rec_ic15_cuda_teacher_v4_fast
  save_epoch_step: 1
  save_batch_model: true
  print_batch_step: 10
  eval_batch_step: [0, 50]
  cal_metric_during_train: true
  calc_epoch_interval: 1
  log_smooth_window: 20
  min_improve_delta: 0.0001
  character_dict_path: assets/dicts/ppocr_keys_v1.txt
  max_text_length: 40
  use_space_char: true
  seed: 1024
  deterministic: true
  teacher_model_dir: E:/codeding/AI/PP-OCRv4/ch_PP-OCRv4_rec_infer
  teacher_paddle_lib_dir: E:/codeding/AI/paddle_inference/paddle/lib
  distill_weight: 0.35
  distill_temperature: 2.0
  strict_teacher_student: true

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 1
  regularizer:
    name: L2
    factor: 0.00003

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 120
            depth: 2
            hidden_dims: 120
            kernel_size: [1, 3]
            use_guide: true
          Head:
            fc_decay: 0.00001
      - NRTRHead:
          nrtr_dim: 384
          max_text_length: 40

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - NRTRLoss:
  weight_1: 1.0
  weight_2: 0.15

Train:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/li/Downloads/ic15_rec/ic15
    label_file_list:
      - C:/Users/li/Downloads/ic15_rec/ic15/gt_train.txt
    delimiter: ' '
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecAug:
      - MultiLabelEncode:
          gtc_encode: NRTRLabelEncode
      - RecResizeImg:
          image_shape: [3, 48, 320]
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  loader:
    batch_size_per_card: 50
    shuffle: true
    drop_last: true
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/li/Downloads/ic15_rec/ic15
    label_file_list:
      - C:/Users/li/Downloads/ic15_rec/ic15/gt_test.txt
    delimiter: ' '
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - MultiLabelEncode:
          gtc_encode: NRTRLabelEncode
      - RecResizeImg:
          image_shape: [3, 48, 320]
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  loader:
    batch_size_per_card: 50
    shuffle: false
    drop_last: false
    num_workers: 4
