Global:
  device: cuda
  use_amp: true
  epoch_num: 30
  save_model_dir: ./output/rec_tiny_overfit_ctc
  save_epoch_step: 5
  print_batch_step: 1
  eval_batch_step: [0, 2]
  cal_metric_during_train: true
  calc_epoch_interval: 1
  log_smooth_window: 20
  save_batch_model: false
  min_improve_delta: 0.00001
  character_dict_path: assets/samples/tiny_rec/dict.txt
  max_text_length: 2
  use_space_char: true
  seed: 1024
  deterministic: true

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Exponential
    learning_rate: 0.001
    gamma: 1.0
  regularizer:
    name: L2
    factor: 0.0

Architecture:
  model_type: rec
  algorithm: CRNN
  Backbone:
    name: MobileNetV3
    model_name: small
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 32
  Head:
    name: CTCHead
    hidden_size: 32

Loss:
  name: CTCLoss

Train:
  dataset:
    name: SimpleDataSet
    data_dir: assets/samples/tiny_rec
    label_file_list:
      - assets/samples/tiny_rec/train.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 48, 192]
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
            - valid_ratio
  loader:
    batch_size_per_card: 2
    shuffle: true
    drop_last: false
    num_workers: 1

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: assets/samples/tiny_rec
    label_file_list:
      - assets/samples/tiny_rec/train.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 48, 192]
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
            - valid_ratio
  loader:
    batch_size_per_card: 2
    shuffle: false
    drop_last: false
    num_workers: 1
