Global:
  epoch_num: 2
  save_model_dir: ./output/tiny_rec
  checkpoints:
  character_dict_path: ../../samples/tiny_rec/dict.txt
  max_text_length: 2
  use_space_char: true

Optimizer:
  lr:
    learning_rate: 0.001

Architecture:
  model_type: rec

Train:
  dataset:
    data_dir: ../../samples/tiny_rec
    label_file_list:
      - ../../samples/tiny_rec/train.txt
    transforms:
      - RecResizeImg:
          image_shape: [3, 48, 192]
  loader:
    batch_size_per_card: 2

Eval:
  dataset:
    data_dir: ../../samples/tiny_rec
    label_file_list:
      - ../../samples/tiny_rec/test.txt
    transforms:
      - RecResizeImg:
          image_shape: [3, 48, 192]
  loader:
    batch_size_per_card: 2
